### ISSUE TITLE
"TypeError: $.isArray is not a function

### ISSUE THREAD

**Issue by dmitry-trefilov** [KirillDZR/bootstrap-ipaddress#1]
```
"jQuery.Deferred exception: $.isArray is not a function", "TypeError: $.isArray is not a function
    at parseIpAddress (http://fiddle.jshell.net/_display/?editor_console=true:246:30)
    at updata (http://fiddle.jshell.net/_display/?editor_console=true:334:31)
    at init (http://fiddle.jshell.net/_display/?editor_console=true:228:13)
    at new IPAddress (http://fiddle.jshell.net/_display/?editor_console=true:602:9)
    at HTMLInputElement.&lt;anonymous&gt; (http://fiddle.jshell.net/_display/?editor_console=true:608:48)
    at Function.each (http://code.jquery.com/jquery-compat-git.js:340:19)
    at jQuery.fn.init.each (http://code.jquery.com/jquery-compat-git.js:168:17)
    at jQuery.fn.init.$.fn.ipaddress (http://fiddle.jshell.net/_display/?editor_console=true:606:21)
    at HTMLDocument.&lt;anonymous&gt; (http://fiddle.jshell.net/_display/?editor_console=true:616:26)
    at mightThrow (http://code.jquery.com/jquery-compat-git.js:3044:29)", undefined
"Script error."
```

**Comment by KirillStr** [comment]
https://jsfiddle.net/v6fhwq9c/1/

**Comment by dmitry-trefilov** [comment]
I don't know what did you change, but now it's working. Thanks!
